In [1]:
from Data.PreProcessing import fetchData
from Data.PreProcessing import fetchLabels
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import validation_curve
data = fetchData("Data/csvData/mar9-data3-PLX-DAQ.csv")
testdata = fetchData("Data/csvData/mar9-data5-PLX-DAQ.csv")

labels = fetchLabels(data,2020,3,9, 48.463522, -123.310644, -8)
testlabels = fetchLabels(testdata,2020,3,9, 48.463522, -123.310644, -8)
colnames=['time','sens1', 'sens2', 'sens3', 'sens4', 'angle1', 'angle2']

from datetime import date

import pandas as pd

datapd = pd.read_csv("Data/csvData/mar9-data3-PLX-DAQ.csv", 
                   delimiter = ",",
                    names=colnames)

colnames=['time','sens1', 'sens2', 'sens3', 'sens4', 'angle1', 'angle2']
datapdtest = pd.read_csv("Data/csvData/mar9-data5-PLX-DAQ.csv", 
                   delimiter = ",",
                    names=colnames)
labelarr=np.array(np.asarray(labels))
labelarrtest=np.array(np.asarray(testlabels))
datapd=datapd.iloc[1:]
datapdtest=datapdtest.iloc[1:]
round1tdata= np.array(np.asarray(testdata))
round1data= np.array(np.asarray(data))
datapd['time'] = datapd['time'].astype(str)
datapd['time']=pd.to_datetime(datapd['time'])
datapdtest['time'] = datapdtest['time'].astype(str)
datapdtest['time']=pd.to_datetime(datapdtest['time'])

labelarr=(labelarr).astype(int)
labelarrtest=(labelarrtest).astype(int)

Test
Test


In [4]:

data1= np.empty((round1data.shape[0],5))
data1[:,0]=round1data[:,0]+round1data[:,1]
data1[:,1]=round1data[:,2]+round1data[:,3]
data1[:,2:5]=round1data[:,6:9]
#data1[:,2]=datapd['time'].apply(lambda x: x.toordinal())


data1test= np.empty((round1tdata.shape[0],5))
data1test[:,0]=round1tdata[:,0]+round1tdata[:,3]
data1test[:,1]=round1tdata[:,1]+round1tdata[:,2]
data1test[:,2:5]=round1tdata[:,6:9]
#data1test[:,2]=datapdtest['time'].apply(lambda x: x.toordinal())


data2= np.empty((round1data.shape[0],5))
data2[:,0]=round1data[:,0]+round1data[:,3]
data2[:,1]=round1data[:,1]+round1data[:,2]
data2[:,2:5]=round1data[:,6:9]
#data2[:,2]=datapd['time'].apply(lambda x: x.toordinal())

data2test= np.empty((round1tdata.shape[0],5))
data2test[:,0]=round1tdata[:,0]+round1tdata[:,3]
data2test[:,1]=round1tdata[:,1]+round1tdata[:,2]
data2test[:,2:5]=round1tdata[:,6:9]
#data2test[:,2]=datapdtest['time'].apply(lambda x: x.toordinal())


data3= np.empty((round1data.shape[0],7))
data3[:,0:4]=round1data[:,0:4]
data3[:,4:7]=round1data[:,6:9]
#data3[:,4]=datapd['time'].apply(lambda x: x.toordinal())

data3test= np.empty((round1tdata.shape[0],7))
data3test[:,0:4]=round1tdata[:,0:4]
data3test[:,4:7]=round1tdata[:,6:9]
#data3test[:,4]=datapdtest['time'].apply(lambda x: x.toordinal())


data4= np.empty((round1data.shape[0],3))
data4=round1data[:,6:9]
#data4[:,0]=datapd['time'].apply(lambda x: x.toordinal())

data4test= np.empty((round1tdata.shape[0],1))
data4test=round1tdata[:,6:9]
#data4test[:,0]=datapdtest['time'].apply(lambda x: x.toordinal())


In [3]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import validation_curve


logresalt=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data1,labelarr[:,0])
logresazm=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data2,labelarr[:,1])
ex1alt=logresalt.predict(data1test)
ex1azm=logresazm.predict(data2test)

logresalt2=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data3,labelarr[:,0])
logresazm2=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data3,labelarr[:,1])
ex2alt=logresalt2.predict(data3test)
ex2azm=logresazm2.predict(data3test)

logresalt3=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data4,labelarr[:,0])
logresazm3=LogisticRegression(C=1e-3,warm_start=True,max_iter=10000).fit(data4,labelarr[:,1])
ex3alt=logresalt3.predict(data4test)
ex3azm=logresazm3.predict(data4test)


ValueError: Found input variables with inconsistent numbers of samples: [53483, 64998]

In [10]:
calclabels=np.empty((ex1alt.shape[0],2))
calclabels[:,0]=ex1alt
calclabels[:,1]=ex1azm
print(calclabels)
print(labelarrtest)
score1=getScore(calclabels,labelarrtest,30)
print(score1)

calclabels=np.empty((ex2alt.shape[0],2))
calclabels[:,0]=ex2alt
calclabels[:,1]=ex2azm
print(calclabels)
print(labelarrtest)
score2=getScore(calclabels,labelarrtest,30)
print(score2)

calclabels=np.empty((ex3alt.shape[0],2))
calclabels[:,0]=ex3alt
calclabels[:,1]=ex3azm
print(calclabels)
print(labelarrtest)
score3=getScore(calclabels,labelarrtest,30)
print(score3)




[[ 31. 211.]
 [ 31. 211.]
 [ 31. 211.]
 ...
 [ 31. 216.]
 [ 31. 216.]
 [ 31. 216.]]
[[ 26 227]
 [ 26 227]
 [ 26 227]
 ...
 [ 21 235]
 [ 21 235]
 [ 21 235]]
Tolerance of 30 degrees
Score: 0.5213806256193557

0.5213806256193557
[[ 31. 211.]
 [ 31. 211.]
 [ 31. 211.]
 ...
 [ 31. 216.]
 [ 31. 216.]
 [ 31. 216.]]
[[ 26 227]
 [ 26 227]
 [ 26 227]
 ...
 [ 21 235]
 [ 21 235]
 [ 21 235]]
Tolerance of 30 degrees
Score: 0.5186881812912514

0.5186881812912514
[[ 31. 211.]
 [ 31. 211.]
 [ 31. 211.]
 ...
 [ 31. 216.]
 [ 31. 216.]
 [ 31. 216.]]
[[ 26 227]
 [ 26 227]
 [ 26 227]
 ...
 [ 21 235]
 [ 21 235]
 [ 21 235]]
Tolerance of 30 degrees
Score: 0.5218854589308752

0.5218854589308752


In [6]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from math import sin
from math import cos

def getScore(calculatedLabels, expectedLabels, degreeVariance):
    score = 0
    total = len(calculatedLabels)
    print("Tolerance of "+str(degreeVariance)+" degrees")
    for i in range (total):
        calculatedAlpha = calculatedLabels[i][0]
        calculatedBeta = calculatedLabels[i][1]
        expectedAlpha = expectedLabels[i][0]
        expectedBeta = expectedLabels[i][1]

        differenceBound = degreeVariance/2

        upperboundAlpha = expectedAlpha + differenceBound
        lowerboundAlpha = expectedAlpha - differenceBound
        upperboundBeta = expectedBeta + differenceBound
        lowerboundBeta = expectedBeta - differenceBound

        if (calculatedAlpha > upperboundAlpha) or (calculatedAlpha < lowerboundAlpha):
            continue
        elif (calculatedBeta > upperboundBeta) or (calculatedBeta < lowerboundBeta):
            continue

        score = score + 1
    print("Score: "+str(score/total)+"\n")
    return score/total

def processLabels(data):
    returnData = []
    elevation = 0
    azimuth = 1
    r = 1
    for entry in data:
        newEntry = []

        x = r * cos(entry[elevation]) * cos(entry[azimuth])
        y = r * cos(entry[elevation]) * sin(entry[azimuth])
        z = r * sin(entry[elevation])
        
        newEntry.append(x)
        newEntry.append(y)
        newEntry.append(z)

        returnData.append(newEntry)
    return returnData


def plotTracing(simpleLabels, complicatedLabels, expectedLabels):
    fig = plt.figure()
    ax = Axes3D(fig)
    simple = np.asarray(processLabels(simpleLabels))
    complicated = np.asarray(processLabels(complicatedLabels))
    expected = np.asarray(processLabels(expectedLabels))

    ax.scatter(expected[:,0], expected[:,1], expected[:,2], marker = 'x', color = 'k')
    ax.scatter(simple[:,0], simple[:,1], simple[:,2], marker = 'o', color = 'r')
    ax.scatter(complicated[:,0], complicated[:,1], complicated[:,2], marker = 'o', color = 'b')
    ax.scatter(0,0,0, marker = 'X', color = 'k')
    
    plt.show()